# ./docker-compose.yml

version: '3'

services:
  
  web:
    image: brunosette7777/oabgame:latest
    container_name: php_web
    build: .
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    build: .

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: voupassar7777
    #  MYSQL_DATABASE: aprovagame
    #  MYSQL_USER: user
    #  MYSQL_PASSWORD: voupassar7777
    ports:
      - "9906:3306"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
