# ./docker-compose.yml

version: '3'

services:
  
  web:
    image: php:7.2.16-apache
    container_name: php_web
    build: .
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
#  www:
    build: .

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: aprovagame
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
